package com.raksha.utility;

import com.raksha.response.ViewInsuranceResponce;
import com.raksha.service.ViewInsuranceService;
import com.raksha.service.ViewInsuranceServiceImple;

public class PDFTemplate {
	
	public static String getHTMLInString(int policyNumber) {
		
		ViewInsuranceService service = new ViewInsuranceServiceImple();
		
		ViewInsuranceResponce res = service.getInsuranceView(policyNumber);
		
		String html ="<html>"
				+"	<head>"
				+"		<style>"
				+"			body {"
				+"				height: 842px;"
				+"				width: 595px;"
				+"				margin-left: auto;"
				+"				margin-right: auto;"
				+"			}"
				+"			th,td {"
				+"				margin-left: 2px;"
				+"				border: 1px solid black;"
				+"				border-collapse: collapse;"
				+"			}"
				+"			table {"
				+"				width: 100%;"
				+"				border: 1px solid black;"
				+"				font-size: 20px;"
				+"			}"
				+"		</style>"
				+"	</head>"
				+"	<body>"
				+"		<div>"
				+"			<h3>RAKSHA</h3><small>© 2020 Copyright: Raksha Vehicle Insurance Pvt. Ltd.</small>"
				+"		</div>"
				+"		<div>"
				+"			<table >"
				+"				<tr>"
				+"					<th>Name </th>"
				+"					<th>Policy Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>joey s tribbiani</td>"
				+"					<td>12309876454</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>E-mail</th>"
				+"					<th>Phone Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>joey@gamil.com</td>"
				+"					<td>1234567890</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Photo ID</th>"
				+"					<th>Photo ID Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>Adhar</td>"
				+"					<td>1234567890</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Vehicle Type</th>"
				+"					<th>Vehicle Registraion Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>bike</td>"
				+"					<td>MH-90-A-1234</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Vehicle Brand</th>"
				+"					<th>Vehicle Model</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>honda</td>"
				+"					<td>activa 5g</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"				<tr>"
				+"					<th>Insurance Type</th>"
				+"					<th>Duration Insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>Third-party</td>"
				+"					<td>2 years</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"				<tr>"
				+"					<th>Insurance Start Date</th>"
				+"					<th>Insurance End Date</th>"
				+"				</tr>"				
				+"				<tr>"
				+"					<td>20-07-2020</td>"
				+"					<td>20-07-2022</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Premium paid</th>"
				+"					<th>Maximum Amount insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>1000</td>"
				+"					<td>50000 </td>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"			</table><br><br>"
				+"			<table>"
				+"				<tr>"
				+"					<td><u>Authority Signature</u>"
				+"					</td>"
				+"					<td ><u>Customer Signature</u></td>"
				+"				</tr>"
				+"				<small>Online copy is electonically signed</small>"
				+"			</table>"
				+"		</div>"
				+"	</body>"
				+"</html>"
				+ "";
		
		return html;
	}
	
}
