package com.raksha.utility;

import com.raksha.response.ViewInsuranceResponce;
import com.raksha.service.ViewInsuranceService;
import com.raksha.service.ViewInsuranceServiceImple;

public class PDFTemplate {
	
	public static String getHTMLInString(int policyNumber) {
		
		ViewInsuranceService service = new ViewInsuranceServiceImple();
		
		ViewInsuranceResponce res = service.getInsuranceView(policyNumber);
		
		String html ="<html>"
				+"	<head>"
				+"		<style> "
				+"			body { "
				+"				height: 842px; "
				+"				width: 700px; "
				+"				margin-left: auto; "
				+"				margin-right: auto; "
				+"			} "
				+"			th,td { "
				+"				border-collapse: collapse;"
				+"				border: 1px solid white; "
				+"			} "
				+"			th{"
				+"			background-color:#ddccff;"
				+"			}"
				+"			td{"
				+"			 padding-top:20px;"
				+"			 padding-bottom:20px;"
				+"			}"
				+"			"
				+"			table { "
				+"				width: 100%; "
				+"				border: 1px solid black; "
				+"				font-size: 20px; "
				+"				text-align: center;"
				+"				border-collapse: collapse;	"
				+"			} "
				+"			h3{"
				+"				color:#513992;"
				+"			}"
				+"			small{"
				+"				color:#969696;"
				+"			}"
				+"			.top{"
				+"				text-align: center;"
				+"			}"
				+"			div{"
				+"			margin-bottom:-180px;"
				+"			}"
				+"		</style> "
				+"	</head>"
				+"	<body>"
				+"		<div class = \"top\">"
				+"			<h3>RAKSHA</h3><small>Â© 2020 Copyright: Raksha Vehicle Insurance Pvt. Ltd.</small>"
				+"		</div>"
				+"			<table >"
				+"				<tr>"
				+"					<th>Name </th>"
				+"					<th>Policy Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserFname()+" "+res.getUserMname()+" "+res.getUserLname()+"</td>"
				+"					<td>"+res.getPolicyNumber()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<th>E-mail</th>"
				+"					<th>Phone Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserEmail()+"</td>"
				+"					<td>"+res.getUserPhone()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<th>Photo ID</th>"
				+"					<th>Photo ID Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserPhotoIdType()+"</td>"
				+"					<td>"+res.getUserPhotoIdNumber()+"</td>"
				+"				</tr><br>"
					
				+"				<tr>"
				+"					<th>Vehicle Type</th>"
				+"					<th>Vehicle Registraion Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getVehicleType()+"</td>"
				+"					<td>"+res.getVehicleRegistrationNumber()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<th>Vehicle Brand</th>"
				+"					<th>Vehicle Model</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getVehicleBrand()+"</td>"
				+"					<td>"+res.getVehicleModel()+"</td>"
				+"				</tr><br>"				
				+"				<tr>"
				+"					<th>Insurance Type</th>"
				+"					<th>Duration Insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getInsuranceType()+"</td>"
				+"					<td>"+res.getInsuranceDuration()+"</td>"
				+"				</tr><br>"			
				+"				<tr>"
				+"					<th>Insurance Start Date</th>"
				+"					<th>Insurance End Date</th>"
				+"				</tr>"				
				+"				<tr>"
				+"					<td>"+res.getInsuranceStartDate()+"</td>"
				+"					<td>"+res.getInsuranceEndDate()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<th>Premium paid</th>"
				+"					<th>Maximum Amount insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getInsurancePremiumPaid()+"</td>"
				+"					<td>"+res.getMaxAmountInsured()+"</td>"
				+"				</tr>"				
				+"			</table><br><br>"
				+"			<table>"
				+"				<tr>"
				+"					<td><u>Authority Signature</u>"
				+"					</td>"
				+"					<td ><u>Customer Signature</u></td>"
				+"				</tr>"
				+"				<small>Online copy is electonically signed</small>"
				+"			</table>"
				+"	</body>"
				+"</html>"
				+ "";

		return html;
	}
	
}
