package com.raksha.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.raksha.response.ViewInsuranceResponce;

@Service
public class PDFTemplateService {
	
	@Autowired
	ViewInsuranceService service;

	public String getHTMLInString(int policyNumber) {
				
		ViewInsuranceResponce res = service.getInsuranceView(policyNumber);
		
		String html ="<html>"
				+"	<head>"
				+"		<style>"
				+"			body {"
				+"				height: 842px;"
				+"				width: 595px;"
				+"				margin-left: auto;"
				+"				margin-right: auto;"
				+"			}"
				+"			th,td {"
				+"				margin-left: 2px;"
				+"				border: 1px solid black;"
				+"				border-collapse: collapse;"
				+"			}"
				+"			table {"
				+"				width: 100%;"
				+"				border: 1px solid black;"
				+"				font-size: 20px;"
				+"			}"
				+"		</style>"
				+"	</head>"
				+"	<body>"
				+"		<div>"
				+"			<h3>RAKSHA</h3><small>© 2020 Copyright: Raksha Vehicle Insurance Pvt. Ltd.</small>"
				+"		</div>"
				+"		<div>"
				+"			<table >"
				+"				<tr>"
				+"					<th>Name </th>"
				+"					<th>Policy Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserFname()+" "+res.getUserMname()+" "+res.getUserLname()+"</td>"
				+"					<td>"+res.getPolicyNumber()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>E-mail</th>"
				+"					<th>Phone Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserEmail()+"</td>"
				+"					<td>"+res.getUserPhone()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Photo ID</th>"
				+"					<th>Photo ID Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getUserPhotoIdType()+"</td>"
				+"					<td>"+res.getUserPhotoIdNumber()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Vehicle Type</th>"
				+"					<th>Vehicle Registraion Number</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getVehicleType()+"</td>"
				+"					<td>"+res.getVehicleRegistrationNumber()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Vehicle Brand</th>"
				+"					<th>Vehicle Model</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getVehicleBrand()+"</td>"
				+"					<td>"+res.getVehicleModel()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"				<tr>"
				+"					<th>Insurance Type</th>"
				+"					<th>Duration Insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getInsuranceType()+"</td>"
				+"					<td>"+res.getInsuranceDuration()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"				<tr>"
				+"					<th>Insurance Start Date</th>"
				+"					<th>Insurance End Date</th>"
				+"				</tr>"				
				+"				<tr>"
				+"					<td>"+res.getInsuranceStartDate()+"</td>"
				+"					<td>"+res.getInsuranceEndDate()+"</td>"
				+"				</tr><br>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"
				+"				<tr>"
				+"					<th>Premium paid</th>"
				+"					<th>Maximum Amount insured</th>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>"+res.getInsurancePremiumPaid()+"</td>"
				+"					<td>"+res.getMaxAmountInsured()+"</td>"
				+"				</tr>"
				+"				<tr>"
				+"					<td>.</td>"
				+"					<td>.</td>"				
				+"				</tr>"				
				+"			</table><br><br>"
				+"			<table>"
				+"				<tr>"
				+"					<td><u>Authority Signature</u>"
				+"					</td>"
				+"					<td ><u>Customer Signature</u></td>"
				+"				</tr>"
				+"				<small>Online copy is electonically signed</small>"
				+"			</table>"
				+"		</div>"
				+"	</body>"
				+"</html>"
				+ "";
		
		return html;
	}
	
}
